theme: jekyll-theme-slate
title: Create a Face Recognition System Using Arcface in Keras
description: see my [face recognition using webcam project in GitHub](https://https://github.com/Iman1221/Face-gender-race-recognition-with-webcam) for training and testing a face recogniton system.
