theme: jekyll-theme-slate
title: Create Your Own Face Recognition System Using Arcface 
description: see my gitub page https://https://github.com/Iman1221/Face-gender-race-recognition-with-webcam for designing a face recognition system in videos
